environment:

  global:
    password: 
      secure: f5/BYn3r6+mnHmEyQLswJ8T8xgiBTqKUKnMDN0OVI69yWD2Sm+TkM5jbCpATbYZL
    

  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"
       

init:
  - "ECHO Python %PYTHON_VERSION% (%PYTHON_ARCH%bit) from %PYTHON%"       

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip.exe --version"
  - "%PYTHON%\\Scripts\\pip install wheel"
  - "%PYTHON%\\Scripts\\wheel.exe version"
  - "%PYTHON%\\Scripts\\pip install pytest"
  - "%PYTHON%\\Scripts\\pip install cython"
  # we need to get nanosvg
  - "git submodule update --init ."

build: off
build_script:
- "%PYTHON%\\python.exe setup.py install"
test_script:
  - "cd tests"
  - "%PYTHON%\\Scripts\\pytest"
  - "cd .."

deploy_script:
    - "echo [pypi] > %USERPROFILE%\\.pypirc"
    - "echo username:ethanhs >> %USERPROFILE%\\.pypirc"
    - "echo password:%password% >> %USERPROFILE%\\.pypirc"
    - "%PYTHON%\\python setup.py sdist bdist_wheel upload"

