environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
    
    password: 
      secure: f5/BYn3r6+mnHmEyQLswJ8T8xgiBTqKUKnMDN0OVI69yWD2Sm+TkM5jbCpATbYZL
    

  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"
       

init:
  - "ECHO Python %PYTHON_VERSION% (%PYTHON_ARCH%bit) from %PYTHON%"       

install:
  - "%PYTHON%\\Scripts\\pip.exe --version"
  - "%PYTHON%\\Scripts\\pip install wheel"
  - "%PYTHON%\\Scripts\\wheel.exe version"
  - "%PYTHON%\\Scripts\\pip install pytest"
  - "%PYTHON%\\Scripts\\pip install cython"

build: off
build_script:
- "%WITH_ENV% %PYTHON%\\python.exe setup.py install"
test_script:
  - "cd tests"
  - "pytest"
  - "cd .."

deploy_script:
    - "echo [pypi] > %USERPROFILE%\\.pypirc"
    - "echo username: IronManMark20 >> %USERPROFILE%\\.pypirc"
    - "echo password: %password% >> %USERPROFILE%\\.pypirc"
    - python setup.py sdist bdist_wheel upload

